

server:
  port: 8888

spring:
  application:
    name: configuration-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArielHern/store-microservices-config-server.git
          clone-on-start: true
          default-label: main
